Trace callables and create protocols
SgtPepper634/protopy pull request #1
Opened 2023-10-09 19:07 UTC by SgtPepper634

- This PR uses a tracer to trace when functions are called and return, in order to generate Protocols when appropriate.
- Protocols are added to the bottom of the file in question (for now).

2023-10-10 08:49 UTC, willfrey requested changes
I think `callable_tracing.py`, `protocols.py` and `shared_types.py` could all be combined into a single module. Since the project is named ProtoPy, perhaps you could consolidate to to `protopy.py`? That would make turning this into a package later a bit more straightforward.

2023-10-10 08:49 UTC, willfrey commented on callable_tracing.py
> +    return
This is a great place for a `match` statement instead of `if`/`elif`/`else`! If you're okay with not supporting versions of Python before 3.10, I'd recommend changing that here.

2023-10-10 08:49 UTC, willfrey commented on main.py
This looks like it's the start of some test code, so perhaps we could move it to a test module? Something like `test_protopy.py`?

2023-10-10 08:52 UTC, willfrey requested changes
I recommend running the `black` formatter over your files. VS Code has support for black nearly out-of-the-box. Some of the lines here are pretty long!

2023-10-10 08:52 UTC, willfrey commented on protocols.py
> +def write_protocols(method_list: MethodList) -> None:
You should extract the inner logic that operates on a single method into its own function! Handle one and then you can apply it to any iterable collection you want.

```suggestion
def generate_protocol(fucn: Callable) -> str:
```

2023-10-10 08:52 UTC, willfrey commented on protocols.py
> +      file.write(f'''
Great use of an f-string here. I recommend using using a `\` character after the initial opening triple-quotes to avoid having the extra newline show up.

```suggestion
      file.write(f'''\
```

2023-10-10 08:53 UTC, willfrey commented
Once it's all consolidated, I suggest moving the code to a package structure (I'll help, don't worry!) and adding some more type annotations for the library code itself.

2023-10-10 08:54 UTC, willfrey commented on callable_tracing.py
> +    for i in range(arg_count):
You can (and should!) iterate directly over `arg_names` instead of using `range`.


```suggestion
    for arg_name in arg_names: 
```

2023-10-10 08:55 UTC, willfrey commented on callable_tracing.py
There's a lot of calls to `print` statements here! Those can be helpful for debugging but you don't want them always printing to stdout in library code. I suggest using the `logging` (or `loguru`) to handle some of that. We can worry about that in a future PR, though!

2023-10-10 14:54 UTC, SgtPepper634 commented on callable_tracing.py
> +    return
@willfrey what do you think about not supporting versions before 3.10? I only did 3.10 in poetry because that was what the default was but technically this project should be able to run on versions 3.5 and above no?

2023-10-10 14:59 UTC, SgtPepper634 commented on callable_tracing.py
> +    for i in range(arg_count):
We talked about this in our call today but `code.co_varnames` includes local variables in addition to the arguments. We agreed the following would be the best solution.

```python
for arg_name in arg_names[:arg_count]:
```

2023-10-10 15:00 UTC, SgtPepper634 commented on callable_tracing.py
Yup of course. Just left them in incase you wanted to run the code and to see what information I was able to produuce with the tracer.

2023-10-10 16:00 UTC, SgtPepper634 commented
> I think `callable_tracing.py`, `protocols.py` and `shared_types.py` could all be combined into a single module. Since the project is named ProtoPy, perhaps you could consolidate to to `protopy.py`? That would make turning this into a package later a bit more straightforward.

@willfrey I will make a new PR for this

2023-10-10 16:01 UTC, SgtPepper634 commented on main.py
Will do this in a new PR

2023-10-10 16:38 UTC, SgtPepper634 commented on protocols.py
> +def write_protocols(method_list: MethodList) -> None:
@willfrey Just so I make sure I understand correctly... Are you saying to split this into two functions where the first receives a `Iterable` of callables from a file and for each one calls a second function that actually generates the protocol for each?

2023-10-10 16:50 UTC, SgtPepper634 commented on protocols.py
> +def write_protocols(method_list: MethodList) -> None:
I'll probably address this in another PR

2023-10-11 01:39 UTC, willfrey commented
Sounds like you'd prefer to make most of these fixes in subsequent PRs, which is fine! Get those up and once you have the test file, I can write the test cases.

2023-10-11 01:40 UTC, merged